### ISSUE TITLE
Mulitple values for insert are not working

### ISSUE THREAD

**Issue by tgalery** [bogdan32x/ZQL#10]
I'm trying to read a file with insert statements of the form:

```
insert into table1 (First,Last) values ('Fred','Smith'),
  ('John','Smith'),
  ('Michael','Smith'),
  ('Robert','Smith');
```

However, this is generating this exception

```
Was expecting:
    ";" ...
    
	at org.gibello.zql.ZqlJJParser.generateParseException(ZqlJJParser.java:3582)
	at org.gibello.zql.ZqlJJParser.jj_consume_token(ZqlJJParser.java:3458)
	at org.gibello.zql.ZqlJJParser.InsertStatement(ZqlJJParser.java:579)
	at org.gibello.zql.ZqlJJParser.SQLStatement(ZqlJJParser.java:178)
	at org.gibello.zql.ZqlJJParser.SQLStatements(ZqlJJParser.java:142)
	at org.gibello.zql.ZqlParser.readStatements(ZqlParser.java:103)
```

and the method that generates the exception is here

```
private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  } ```

**Comment by tgalery** [comment]
I'm wondering whether commas are not defined and I'd need to define that somewhere ?

**Comment by bogdan32x** [comment]
Hi @tgalery will be checking it asap. I'll write some unit tests with your testcase

**Comment by tgalery** [comment]
Cheers, but if you are swamped and want to point me towards the right direction I can try to help (I never used javacc before).

**Comment by bogdan32x** [comment]
First of all you should start by reading a bit about JavaCC at: 
http://www.engr.mun.ca/~theo/JavaCC-FAQ/javacc-faq-moz.htm

**Comment by bogdan32x** [comment]
// InsertStatement ::= INSERT INTO TableReference
//   [ "(" TableColumn (, TableColumn)* ")" ]
//   ValueSpec | SelectStatement
// ValueSpec ::= VALUES ( SQLExpressionList )
ZInsert InsertStatement():
{
  ZInsert ins;
  String s;
  List v;
  ZQuery q;
}
{
  "INSERT" "INTO" s = TableReference() { ins = new ZInsert(s); }
   ["(" s = TableColumn() { v = new ArrayList(); v.add(s); }
    ("," s = TableColumn() { v.add(s); } )* ")" { ins.addColumns(v); } ]
   ( "VALUES" "(" v = SQLExpressionList() ")"
     { ZExpression e = new ZExpression(",");
       e.setOperands(v); ins.addValueSpec(e); }
     |
     q = SelectStatement() { ins.addValueSpec(q); }
   )
   ";" { return ins; }
}

This is the part we need to update to support multiline inserts

**Comment by tgalery** [comment]
Are you talking about this line https://github.com/bogdan32x/ZQL/blob/master/src/main/javacc/ZqlJJParser.jj#L391 ?

It seems to me we would need to parse the way commas are handled in the values section in a few lines above https://github.com/bogdan32x/ZQL/blob/master/src/main/javacc/ZqlJJParser.jj#L394 . At the moment commas are separating just different values `(v1, v2, v3)`, not between sets of different values ` (v1, v2), (v3, v4)`

**Comment by tgalery** [comment]
If I get things right, `"VALUES" "(" v = SQLExpressionList() ")"` just  gets a single sequence of values inside one parenthesis, would need to allow that to be more than one

**Comment by bogdan32x** [comment]
Yes you got it right. We might need to add a wrapper for multi-line values.

**Comment by tgalery** [comment]
Ok, so this is my first stab at trying to fix it https://github.com/tgalery/ZQL/commit/69d6e004c935732aa119df980c97654741ad0189 . It fixes the exception, but the behaviours is not right, the last set of values overrides the remainder values. Is there a way to initialize an array list just after "VALUES" and just use something like `v.add(SqlStatement)` for each of the matches ?

**Comment by bogdan32x** [comment]
Yes it is possible. In order to have all values we should have a List of pairs, where each pair is a row from the multiline insert. As it is now we only have a List for the first set of values. That's why I said that maybe a wrapper over it might not hurt. 

E.g:
```java
class ZInsertValuePair {
 List valuePair;
}
```
And in the constructor pass the value group `v.add(new ZInsertValuePair(SQLExpressionList())`
So by having this we can extend the initial List to hold full entries instead of a single set of values

**Comment by tgalery** [comment]
Kind of tried your suggestion, so that line became something like `( "VALUES" "(" v = ZInsertValuePair() ")" ( "," "(" v.add(SQLExpressionList()) ")" )*`, whereas the little class is: this

```
List ZInsertValuePair():
{
  List valuePair = new ArrayList();
  List e;
}
{
    e = SQLExpressionList() { valuePair.add(e); }
    { return valuePair; }
}
```

However this generates an error `org.javacc.parser.ParseException: Encountered " <IDENTIFIER> "v "  "." ". "  <IDENTIFIER> "add "  "(" "( "  <IDENTIFIER> "SQLExpressionList "  "(" "( "  ")" ") "  ")" ") "  <STRING_LITERAL> "\")\" "" at line 394, column 56.` I will try to handle the unpacking of the extra values inside that class
