### ISSUE TITLE
Parsing error when parsing backticks

### ISSUE THREAD

**Issue by tgalery** [bogdan32x/ZQL#13]
Error generated when parsing lines of the following form
`INSERT INTO `langlinks` VALUES (3354695,'vi','Giải Lilienfeld'),....`

**Comment by tgalery** [comment]
```
Exception in thread "main" org.gibello.zql.TokenMgrError: Lexical error at line 1, column 13.  Encountered: "`" (96), after : ""
    at org.gibello.zql.ZqlJJParserTokenManager.getNextToken(ZqlJJParserTokenManager.java:1803)
    at org.gibello.zql.ZqlJJParser.jj_ntk(ZqlJJParser.java:3503)
    at org.gibello.zql.ZqlJJParser.OracleObjectName(ZqlJJParser.java:655)
    at org.gibello.zql.ZqlJJParser.TableReference(ZqlJJParser.java:719)
    at org.gibello.zql.ZqlJJParser.InsertStatement(ZqlJJParser.java:533)
    at org.gibello.zql.ZqlJJParser.SQLStatement(ZqlJJParser.java:178)
    at org.gibello.zql.ZqlJJParser.SQLStatements(ZqlJJParser.java:142)
    at org.gibello.zql.ZqlParser.readStatements(ZqlParser.java:103)
```
